using FoundationaLLM.Common.Exceptions;
using Microsoft.AspNetCore.Http;

namespace FoundationaLLM.SemanticKernel.Core.Exceptions
{
    /// <summary>
    /// Represents an error generated by the Semantic Kernel service.
    /// </summary>
    public class SemanticKernelException : HttpStatusCodeException
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GatewayException"/> class with a default message.
        /// </summary>
        public SemanticKernelException() : this(null, StatusCodes.Status500InternalServerError)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SemanticKernelException"/> class with its message set to <paramref name="message"/>.
        /// </summary>
        /// <param name="message">A string that describes the error.</param>
        /// <param name="statusCode">The HTTP status code associated with the exception.</param>
        public SemanticKernelException(string? message, int statusCode = StatusCodes.Status500InternalServerError) :
            base(message, statusCode)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SemanticKernelException"/> class with its message set to <paramref name="message"/>.
        /// </summary>
        /// <param name="message">A string that describes the error.</param>
        /// <param name="innerException">The exception that is the cause of the current exception.</param>
        /// <param name="statusCode">The HTTP status code associated with the exception.</param>
        public SemanticKernelException(string? message, Exception? innerException, int statusCode = StatusCodes.Status500InternalServerError) :
            base(message, innerException, statusCode)
        {
        }
    }
}
