using FoundationaLLM.Common.Models.ResourceProviders;

namespace FoundationaLLM.Attachment.Models
{
    /// <summary>
    /// Contains a reference to an attachment.
    /// </summary>
    public class AttachmentReference : ResourceReference
    {
        /// <summary>
        /// The original file name of the attachment.
        /// This is useful because the resource name is generated by the system
        /// and may not be the same as the original file name.
        /// </summary>
        public string OriginalFilename { get; set; } = string.Empty;

        /// <summary>
        /// The mime content type of the attachment.
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// Indicates an optional secondary provider for the attachment.
        /// </summary>
        /// <remarks>
        /// The only secondary provider currently supported is the FoundationaLLM.AzureOpenAI provider.
        /// </remarks>
        public string? SecondaryProvider { get; set; }
    }
}
