using FoundationaLLM.Common.Constants.ResourceProviders;
using FoundationaLLM.Common.Exceptions;
using FoundationaLLM.Common.Models.ResourceProviders;
using FoundationaLLM.Common.Models.ResourceProviders.Attachment;
using System.Text.Json.Serialization;

namespace FoundationaLLM.Attachment.Models
{
    /// <summary>
    /// Contains a reference to an attachment.
    /// </summary>
    public class AttachmentReference : ResourceReference
    {
        /// <summary>
        /// The original file name of the attachment.
        /// This is useful because the resource name is generated by the system
        /// and may not be the same as the original file name.
        /// </summary>
        public string OriginalFilename { get; set; } = string.Empty;

        /// <summary>
        /// The mime content type of the attachment.
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// Indicates an optional secondary provider for the attachment.
        /// </summary>
        /// <remarks>
        /// The only secondary provider currently supported is the FoundationaLLM.AzureOpenAI provider.
        /// </remarks>
        public string? SecondaryProvider { get; set; }

        /// <summary>
        /// The object type of the resource.
        /// </summary>
        [JsonIgnore]
        public override Type ResourceType =>
            Type switch
            {
                AttachmentTypes.File => typeof(AttachmentFile),
                _ => throw new ResourceProviderException($"The resource type {Type} is not supported.")
            };
    }
}
