using FoundationaLLM.Common.Interfaces;

namespace FoundationaLLM.Common.Constants
{
    /// <summary>
    /// Name constants used for the key names of the dictionary generated by <see cref="IHttpClientFactoryService"/> implementations.
    /// </summary>
    public static class HttpClientFactoryServiceKeyNames
    {
        /// <summary>
        /// The dictionary key identifying the authentication type of an HTTP client.
        /// </summary>
        public const string AuthenticationType = "AuthenticationType";

        /// <summary>
        /// The dictionary key identifying the endpoint of an HTTP client.
        /// </summary>
        public const string Endpoint = "Endpoint";

        /// <summary>
        /// The dictionary key identifying the API key of an HTTP client.
        /// </summary>
        public const string APIKey = "APIKey";

        /// <summary>
        /// The dictionary key identifying the timeout in seconds associated with an HTTP client.
        /// </summary>
        public const string TimeoutSeconds = "TimeoutSeconds";
    }
}
