/** Inputs **/
@description('Azure Monitor Workspace Resource Id')
param azureMonitorWorkspaceResourceId string

@description('Location for all resources')
param location string

@description('Private DNS Zones for private endpoint')
param privateDnsZones array

@description('Resource suffix for all resources')
param resourceSuffix string

@description('Subnet Id for private endpoint')
param subnetId string

@description('Tags for all resources')
param tags object

@description('Timestamp for nested deployments')
param timestamp string = utcNow()

/** Locals **/
@description('The Resource Name')
var name = replace('${serviceType}-${resourceSuffix}', '-', '')

@description('The Resource Service Type token')
var serviceType = 'amg'

/** Resources **/
resource main 'Microsoft.Dashboard/grafana@2022-10-01-preview' = {
  identity: { type: 'SystemAssigned' }
  location: location
  name: name
  sku: { name: 'Standard' }
  tags: tags

  properties: {
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'

    grafanaConfigurations: {
      smtp: { enabled: false }
    }

    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: [
        {
          azureMonitorWorkspaceResourceId: azureMonitorWorkspaceResourceId
        }
      ]
    }
  }
}

/** Nested Modules **/
@description('Private endpoint for the resource.')
module privateEndpoint 'utility/privateEndpoint.bicep' = [for zone in privateDnsZones: {
  name: 'pe-${main.name}-${zone.key}-${timestamp}'
  params: {
    groupId: zone.key
    location: location
    privateDnsZones: filter(privateDnsZones, item => item.key == zone.key)
    subnetId: subnetId
    tags: tags

    service: {
      id: main.id
      name: main.name
    }
  }
}]
