# Default values for core-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
serviceAccountName: core-job
image:
  repository: ghcr.io/solliancenet/foundationallm/core-job
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  protocol: https
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors:            "true"
    nginx.ingress.kubernetes.io/secure-backends:        "true"
    nginx.ingress.kubernetes.io/cors-allow-origin:     "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers:     "*"
    nginx.ingress.kubernetes.io/cors-allow-methods:     "*"
  tls:
  - secretName: tls-prod

env:
  configmap:
    - name: AZURE_CLIENT_ID
  secret:
    - name: FoundationaLLM_AppConfig_ConnectionString
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production