using System.Text.Json.Serialization;

namespace FoundationaLLM.Common.Models.Orchestration.Response
{
    /// <summary>
    /// Represents the result of an analysis.
    /// </summary>
    public class AnalysisResult
    {
        /// <summary>
        /// The input provided to the tool for analysis.
        /// </summary>
        [JsonPropertyName("tool_input")]
        public required string ToolInput { get; set; }

        /// <summary>
        /// The output generated by the tool after analysis.
        /// </summary>
        [JsonPropertyName("tool_output")]
        public required string ToolOutput { get; set; }

        /// <summary>
        /// The category of the agent's capability that was used in the analysis.
        /// </summary>
        [JsonPropertyName("agent_capability_category")]
        public required string AgentCapabilityCategory { get; set; }

        /// <summary>
        /// The name of the tool that performed the analysis.
        /// </summary>
        [JsonPropertyName("tool_name")]
        public string? ToolName { get; set; }
    }
}
