namespace FoundationaLLM.Management.Models.Configuration
{
    /// <summary>
    /// Stores the Azure Cosmos DB settings from the app configuration.
    /// </summary>
    public record CosmosDbSettings
    {
        /// <summary>
        /// The Azure Cosmos DB endpoint URL.
        /// </summary>
        public required string Endpoint { get; init; }
        /// <summary>
        /// The Azure Cosmos DB key.
        /// </summary>
        public required string Key { get; init; }
        /// <summary>
        /// The name of the Azure Cosmos DB database.
        /// </summary>
        public required string Database { get; init; }
        /// <summary>
        /// Specifies whether to enable Azure Cosmos DB tracing. Disabling tracing reduces
        /// the number of logs generated by the Azure Cosmos DB SDK.
        /// </summary>
        public bool EnableTracing { get; init; }
    }
}
