using FoundationaLLM.Common.Exceptions;
using Microsoft.AspNetCore.Http;

namespace FoundationaLLM.State.Exceptions
{
    /// <summary>
    /// Represents an error generated by the FoundationaLLM State service.
    /// </summary>
    public class StateException : HttpStatusCodeException
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StateException"/> class with a default message.
        /// </summary>
        public StateException() : this(null, StatusCodes.Status500InternalServerError)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StateException"/> class with its message set to <paramref name="message"/>.
        /// </summary>
        /// <param name="message">A string that describes the error.</param>
        /// <param name="statusCode">The HTTP status code associated with the exception.</param>
        public StateException(string? message, int statusCode = StatusCodes.Status500InternalServerError) :
            base(message, statusCode)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StateException"/> class with its message set to <paramref name="message"/>.
        /// </summary>
        /// <param name="message">A string that describes the error.</param>
        /// <param name="innerException">The exception that is the cause of the current exception.</param>
        /// <param name="statusCode">The HTTP status code associated with the exception.</param>
        public StateException(string? message, Exception? innerException, int statusCode = StatusCodes.Status500InternalServerError) :
            base(message, innerException, statusCode)
        {
        }
    }
}
