appConfig:
  uri: {{appConfigEndpoint}}
  connectionString: {{appConfigConnectionString}}
  rwConnectionString: {{appConfigRWConnectionString}}
azureWorkloadIdentity:
  orchestrationApiClientId: {{orchestrationApiMiClientId}}
  agentHubApiClientId: {{agentHubApiMiClientId}}
  chatUiClientId: {{chatUiMiClientId}}
  coreApiClientId: {{coreApiMiClientId}}
  coreJobClientId: {{coreJobMiClientId}}
  dataSourceHubApiClientId: {{dataSourceHubApiMiClientId}}
  gatekeeperApiClientId: {{gatekeeperApiMiClientId}}
  gatekeeperIntegrationApiMiClientId: {{gatekeeperIntegrationApiMiClientId}}
  langChainApiClientId: {{langChainApiMiClientId}}
  managementApiClientId: {{managementApiMiClientId}}
  managementUiClientId: {{managementUiMiClientId}}
  promptHubApiClientId: {{promptHubApiMiClientId}}
  semanticKernelApiClientId: {{semanticKernelApiMiClientId}}
  vectorizationApiClientId: {{vectorizationApiMiClientId}}
  vectorizationJobClientId: {{vectorizationJobMiClientId}}
  authorizationApiClientId: {{authorizationApiMiClientId}}
  tenantId: {{tenantId}}
apihost: {{serviceHostname}}
authKeyvaultUri: {{authKeyvaultUri}}
baseUrl: {{serviceBaseUrl}}
instanceId: {{instanceId}}

ingress:
  enabled: false
