appConfig:
  uri: {{appConfigEndpoint}}
  connectionString: {{appConfigConnectionString}}
  rwConnectionString: {{appConfigRWConnectionString}}
azureWorkloadIdentity:
  agentHubApiClientId: {{agentHubApiMiClientId}}
  chatUiClientId: {{chatUiMiClientId}}
  coreApiClientId: {{coreApiMiClientId}}
  coreJobClientId: {{coreJobMiClientId}}
  dataSourceHubApiClientId: {{dataSourceHubApiMiClientId}}
  gatekeeperApiClientId: {{gatekeeperApiMiClientId}}
  gatekeeperIntegrationApiClientId: {{gatekeeperIntegrationApiMiClientId}}
  gatewayApiClientId: {{gatewayApiMiClientId}}
  gatewayAdapterApiClientId: {{gatewayAdapterApiMiClientId}}
  langChainApiClientId: {{langChainApiMiClientId}}
  managementApiClientId: {{managementApiMiClientId}}
  managementUiClientId: {{managementUiMiClientId}}
  orchestrationApiClientId: {{orchestrationApiMiClientId}}
  promptHubApiClientId: {{promptHubApiMiClientId}}
  semanticKernelApiClientId: {{semanticKernelApiMiClientId}}
  stateApiClientId: {{stateApiMiClientId}}
  vectorizationApiClientId: {{vectorizationApiMiClientId}}
  vectorizationJobClientId: {{vectorizationJobMiClientId}}
  authorizationApiClientId: {{authorizationApiMiClientId}}
  tenantId: {{tenantId}}
authKeyvaultUri: {{authKeyvaultUri}}

ingress:
  enabled: false
