using FoundationaLLM.Common.Exceptions;
using FoundationaLLM.Common.Interfaces;
using FoundationaLLM.Common.Models.Configuration.CosmosDB;
using FoundationaLLM.Common.Models.Vectorization;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.SemanticKernel.Connectors.AzureCosmosDBNoSQL;
using Microsoft.SemanticKernel.Memory;
using System.Collections.ObjectModel;
using System.Text.Json;
using Azure.ResourceManager;
using Azure.ResourceManager.CosmosDB;
using Embedding = Microsoft.Azure.Cosmos.Embedding;
using FoundationaLLM.Common.Authentication;
using Azure.Core;
using Microsoft.Graph.Models;

#pragma warning disable SKEXP0001, SKEXP0020

namespace FoundationaLLM.SemanticKernel.Core.Services.Indexing
{
    /// <summary>
    /// Provides vector embedding indexing based on the Azure Cosmos DB NoSQL API.
    /// </summary>
    public class AzureCosmosDBNoSQLIndexingService : IIndexingService
    {
        private readonly CosmosDbSettings _settings;
        private readonly ILogger<AzureCosmosDBNoSQLIndexingService> _logger;
        private readonly AzureCosmosDBNoSQLMemoryStore _memoryStore;
        private readonly CosmosClient _client;
        private readonly ArmClient _armClient;

        /// <summary>
        /// Creates a new <see cref="AzureCosmosDBNoSQLIndexingService"/> instance.
        /// </summary>
        /// <param name="options">The <see cref="IOptions{TOptions}"/> providing configuration settings.</param>
        /// <param name="logger">The <see cref="ILogger"/> used for logging.</param>
        public AzureCosmosDBNoSQLIndexingService(
            IOptions<CosmosDbSettings> options,
            CosmosClient client,
            ILogger<AzureCosmosDBNoSQLIndexingService> logger)
        {
            _settings = options.Value;
            _logger = logger;
            _client = client;
            _memoryStore = CreateMemoryStore();

            //_armClient = new ArmClient(DefaultAuthentication.AzureCredential);
            //var cosmosDBSqlContainerResourceId = CosmosDBSqlContainerResource.CreateResourceIdentifier();
            //var cosmosDBSqlContainer = _armClient.GetCosmosDBSqlContainerResource(cosmosDBSqlContainerResourceId);
        }

        /// <inheritdoc/>
        public async Task<List<string>> IndexEmbeddingsAsync(EmbeddedContent embeddedContent, string indexName)
        {
            if (!await _memoryStore.DoesCollectionExistAsync(indexName, default).ConfigureAwait(false))
            {
                await _memoryStore.CreateCollectionAsync(indexName, default).ConfigureAwait(false);
            }

            var indexIds = new List<string>();
            var memoryRecords = embeddedContent.ContentParts.Select(cp => MemoryRecord.LocalRecord(
                cp.Id,
                cp.Content,
                "Generated by FoundationaLLM.",
                cp.Embedding.Vector,
                JsonSerializer.Serialize(embeddedContent.ContentId),
                embeddedContent.ContentId.UniqueId,
                DateTimeOffset.UtcNow)).ToList();

            await foreach (var id in _memoryStore.UpsertBatchAsync(
                indexName, memoryRecords))
            {
                indexIds.Add(id);
            }

            return indexIds;
        }

        private void ValidateDatabase(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                _logger.LogCritical("The Azure Cosmos DB vector database name is invalid.");
                throw new ConfigurationValueException("The Azure Cosmos DB vector database name is invalid.");
            }
        }

        /// <summary>
        /// Creates an <see cref="AzureCosmosDBNoSQLMemoryStore"/> instance using the injected
        /// <see cref="CosmosClient"/> and <see cref="CosmosDbSettings"/>.
        /// </summary>
        /// <returns></returns>
        private AzureCosmosDBNoSQLMemoryStore CreateMemoryStore()
        {
            ValidateDatabase(_settings.VectorDatabase);
            return new AzureCosmosDBNoSQLMemoryStore(
                _client,
                _settings.VectorDatabase!,
                new VectorEmbeddingPolicy(
                    new Collection<Embedding>(
                    [
                        new Embedding()
                        {
                            Path = "/embedding",
                            DataType = VectorDataType.Float32,
                            DistanceFunction = DistanceFunction.Cosine,
                            Dimensions = 3072
                        }
                    ])),
                new IndexingPolicy()
                {
                    VectorIndexes =
                    [
                        new VectorIndexPath()
                        {
                            Path = "/embedding",
                            Type = VectorIndexType.QuantizedFlat
                        }
                    ]
                }
            );
        }
    }
}
