name: Publish NuGet Packages

on:
  workflow_dispatch: {}

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Make versioning script executable
      run: chmod +x ./versioning.sh

    - name: Run versioning script
      run: ./versioning.sh
      id: versioning
